name 'euca.clc'
maintainer 'Samuel Chen'
maintainer_email 'wei.chen11@hp.com'
license 'all_rights'
description 'Installs/Configures euca.clc'
long_description 'Installs/Configures euca.clc'
version '0.1.0'
