name             'euca.repo'
maintainer       'Samuel Chen'
maintainer_email 'samuelchen@hp.com'
license          'all_rights'
description      'Installs/Configures euca.repo'
long_description 'Installs/Configures Eucalyptus Repo Server'
version          '0.1.0'

#depends 'apache2', '~> 3.0.1'
depends 'iptables', '~> 0.14.1'
depends 'selinux', '~> 0.9.0'
